license="MIT"
modLoader="javafml"
loaderVersion="47"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees/issues"

[[mods]]
modId="dt_mario_mixup"
version="${file.jarVersion}"
displayName="Dynamic Trees for Mario Mixup"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamictrees"
logoFile="logo.png"
credits=""
authors="WenXin2"
description='''
Adds Dynamic Trees compatibility for Mario Mixup.
'''

[[dependencies.dt_mario_mixup]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_mario_mixup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_mario_mixup]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dt_mario_mixup]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[1.2.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dt_mario_mixup]]
    modId="mario"
    mandatory=true
    versionRange="[1.10.0,)"
    ordering="AFTER"
    side="BOTH"